name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout du code
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: src-front/package-lock.json

      - name: 📦 Installation des dépendances
        run: |
          cd src-front
          npm install

      - name: 🏗️ Build du projet
        run: |
          cd src-front
          npm run build
        env:
          # On lie le frontend à ton backend Azure
          REACT_APP_API_URL: https://job-manager-api-dkb7cvcvavfqc5cp.francecentral-01.azurewebsites.net

      - name: 🚀 Déploiement sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src-front/build
          branch: gh-pages
